# Generated by Django 2.0.7 on 2020-09-14 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanbagisapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='confirmed',
            field=models.BooleanField(default=False, help_text='Onaylı kullanıcı'),
        ),
    ]
